### ISSUE TITLE
翻译模板

### ISSUE THREAD

**Issue by enningxie** [apachecn/stanford-cs224n-notes-zh#2]
有标准的翻译模板吗？用于参考那种。

**Comment by AllenZYJ** [comment]
参考组织其他同类型文档即可，我们后期会做整理

在 2019年6月11日，下午12:48，Coolixz <notifications@github.com<mailto:notifications@github.com>> 写道：


有标准的翻译模板吗？用于参考那种。

**Comment by enningxie** [comment]
ok

**Comment by AllenZYJ** [comment]
> ok

style下面也有哦
